[dev]
63.180.23.18

[prod]
3.72.28.8

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/var/jenkins_home/.ssh/devops-final-key-v2.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

