[dev]
35.157.237.31

[prod]
18.185.156.57

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/var/jenkins_home/.ssh/devops-final-key-v2.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

